# Generated by Django 6.0 on 2025-12-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeoStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_type', models.CharField(choices=[('innovation', 'Innovation'), ('personal', 'Personal'), ('research', 'Research'), ('vision', 'Vision')], max_length=20)),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('reading_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'NeoStory',
                'verbose_name_plural': 'NeoStories',
            },
        ),
    ]
