# Generated by Django 6.0 on 2025-12-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robosharx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robosharxarticle',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='covers/'),
        ),
    ]
