# Generated by Django 6.0 on 2025-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_status', models.CharField(choices=[('idea', 'Idea'), ('development', 'Development'), ('beta', 'Beta'), ('live', 'Live'), ('paused', 'Paused')], default='idea', max_length=20)),
                ('about_project', models.TextField()),
                ('problem_statement', models.TextField(blank=True)),
                ('solution_overview', models.TextField(blank=True)),
                ('project_lead', models.CharField(max_length=150)),
                ('team_members', models.TextField(blank=True, help_text='Comma-separated names')),
                ('technology_stack', models.TextField(help_text='Comma-separated tech (e.g. Django, Next.js, Postgres)')),
                ('repository_url', models.URLField(blank=True)),
                ('live_demo_url', models.URLField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_release_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='0 to 100')),
            ],
            options={
                'verbose_name': 'Neo Project',
                'verbose_name_plural': 'Neo Projects',
            },
        ),
    ]
