# Generated by Django 6.0 on 2025-12-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartupStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup_name', models.CharField(max_length=200)),
                ('founder_name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('seed', 'Seed'), ('series_a', 'Series A'), ('growth', 'Growth')], max_length=20)),
                ('key_learnings', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Startup Story',
                'verbose_name_plural': 'Startup Stories',
            },
        ),
    ]
